{
    "name": "DeployFleet UI",
    "version": "19.0.1.0.0",
    "category": "DeployFleet",
    "summary": "Shared OWL design-system tokens and component library for DeployFleet's frontend",
    "author": "DeployFleet",
    "license": "LGPL-3",
    "depends": ["web", "deployfleet_core"],
    "data": [
        "views/deployfleet_ui_showcase_views.xml",
        "views/deployfleet_ui_mega_menu_views.xml",
        "views/deployfleet_ui_mission_control_views.xml",
        "views/deployfleet_ui_dispatch_board_views.xml",
        "views/deployfleet_ui_fleet_command_center_views.xml",
        "views/deployfleet_ui_copilot_console_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "deployfleet_ui/static/src/scss/tokens.scss",
            "deployfleet_ui/static/src/scss/animations.scss",
            "deployfleet_ui/static/src/components/**/*.scss",
            "deployfleet_ui/static/src/components/**/*.js",
            "deployfleet_ui/static/src/components/**/*.xml",
            "deployfleet_ui/static/src/showcase/*.scss",
            "deployfleet_ui/static/src/showcase/*.js",
            "deployfleet_ui/static/src/showcase/*.xml",
            "deployfleet_ui/static/src/command_palette/*.js",
            "deployfleet_ui/static/src/mega_menu/*.scss",
            "deployfleet_ui/static/src/mega_menu/*.js",
            "deployfleet_ui/static/src/mega_menu/*.xml",
            "deployfleet_ui/static/src/launcher/*.scss",
            "deployfleet_ui/static/src/launcher/*.js",
            "deployfleet_ui/static/src/launcher/*.xml",
            "deployfleet_ui/static/src/mission_control/*.scss",
            "deployfleet_ui/static/src/mission_control/*.js",
            "deployfleet_ui/static/src/mission_control/*.xml",
            "deployfleet_ui/static/src/dispatch_board/*.scss",
            "deployfleet_ui/static/src/dispatch_board/*.js",
            "deployfleet_ui/static/src/dispatch_board/*.xml",
            "deployfleet_ui/static/src/fleet_command_center/*.scss",
            "deployfleet_ui/static/src/fleet_command_center/*.js",
            "deployfleet_ui/static/src/fleet_command_center/*.xml",
            "deployfleet_ui/static/src/copilot_rail/*.scss",
            "deployfleet_ui/static/src/copilot_rail/*.js",
            "deployfleet_ui/static/src/copilot_rail/*.xml",
            "deployfleet_ui/static/src/copilot_console/*.scss",
            "deployfleet_ui/static/src/copilot_console/*.js",
            "deployfleet_ui/static/src/copilot_console/*.xml",
        ],
    },
}
