{
    "name": "DeployFleet UI",
    "version": "19.0.1.0.0",
    "category": "DeployFleet",
    "summary": "Shared OWL design-system tokens and component library for DeployFleet's frontend",
    "author": "DeployFleet",
    "license": "LGPL-3",
    "depends": ["web", "deployfleet_core"],
    "data": [
        "views/deployfleet_ui_showcase_views.xml",
        "views/deployfleet_ui_mega_menu_views.xml",
        "views/deployfleet_ui_mission_control_views.xml",
        "views/deployfleet_ui_dispatch_board_views.xml",
        "views/deployfleet_ui_fleet_command_center_views.xml",
        "views/deployfleet_ui_copilot_console_views.xml",
        "views/deployfleet_ui_driver_scorecards_views.xml",
        "views/deployfleet_ui_workshop_board_views.xml",
        "views/deployfleet_ui_parts_registry_views.xml",
        "views/deployfleet_ui_asset_registry_views.xml",
        "views/deployfleet_ui_vehicle_types_workspace_views.xml",
        "views/deployfleet_ui_fuel_intelligence_views.xml",
        "views/deployfleet_ui_tyre_manager_views.xml",
        "views/deployfleet_ui_insurance_center_views.xml",
        "views/deployfleet_ui_maintenance_planner_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "deployfleet_ui/static/src/scss/tokens.scss",
            "deployfleet_ui/static/src/scss/animations.scss",
            "deployfleet_ui/static/src/components/**/*.scss",
            "deployfleet_ui/static/src/components/**/*.js",
            "deployfleet_ui/static/src/components/**/*.xml",
            "deployfleet_ui/static/src/showcase/*.scss",
            "deployfleet_ui/static/src/showcase/*.js",
            "deployfleet_ui/static/src/showcase/*.xml",
            "deployfleet_ui/static/src/command_palette/*.js",
            "deployfleet_ui/static/src/mega_menu/*.scss",
            "deployfleet_ui/static/src/mega_menu/*.js",
            "deployfleet_ui/static/src/mega_menu/*.xml",
            "deployfleet_ui/static/src/launcher/*.scss",
            "deployfleet_ui/static/src/launcher/*.js",
            "deployfleet_ui/static/src/launcher/*.xml",
            "deployfleet_ui/static/src/mission_control/*.scss",
            "deployfleet_ui/static/src/mission_control/*.js",
            "deployfleet_ui/static/src/mission_control/*.xml",
            "deployfleet_ui/static/src/dispatch_board/*.scss",
            "deployfleet_ui/static/src/dispatch_board/*.js",
            "deployfleet_ui/static/src/dispatch_board/*.xml",
            "deployfleet_ui/static/src/fleet_command_center/*.scss",
            "deployfleet_ui/static/src/fleet_command_center/*.js",
            "deployfleet_ui/static/src/fleet_command_center/*.xml",
            "deployfleet_ui/static/src/copilot_rail/*.scss",
            "deployfleet_ui/static/src/copilot_rail/*.js",
            "deployfleet_ui/static/src/copilot_rail/*.xml",
            "deployfleet_ui/static/src/copilot_console/*.scss",
            "deployfleet_ui/static/src/copilot_console/*.js",
            "deployfleet_ui/static/src/copilot_console/*.xml",
            "deployfleet_ui/static/src/driver_scorecards/*.scss",
            "deployfleet_ui/static/src/driver_scorecards/*.js",
            "deployfleet_ui/static/src/driver_scorecards/*.xml",
            "deployfleet_ui/static/src/workshop_board/*.scss",
            "deployfleet_ui/static/src/workshop_board/*.js",
            "deployfleet_ui/static/src/workshop_board/*.xml",
            "deployfleet_ui/static/src/parts_registry/*.scss",
            "deployfleet_ui/static/src/parts_registry/*.js",
            "deployfleet_ui/static/src/parts_registry/*.xml",
            "deployfleet_ui/static/src/asset_registry/*.scss",
            "deployfleet_ui/static/src/asset_registry/*.js",
            "deployfleet_ui/static/src/asset_registry/*.xml",
            "deployfleet_ui/static/src/vehicle_types_workspace/*.scss",
            "deployfleet_ui/static/src/vehicle_types_workspace/*.js",
            "deployfleet_ui/static/src/vehicle_types_workspace/*.xml",
            "deployfleet_ui/static/src/fuel_intelligence/*.scss",
            "deployfleet_ui/static/src/fuel_intelligence/*.js",
            "deployfleet_ui/static/src/fuel_intelligence/*.xml",
            "deployfleet_ui/static/src/tyre_manager/*.scss",
            "deployfleet_ui/static/src/tyre_manager/*.js",
            "deployfleet_ui/static/src/tyre_manager/*.xml",
            "deployfleet_ui/static/src/insurance_center/*.scss",
            "deployfleet_ui/static/src/insurance_center/*.js",
            "deployfleet_ui/static/src/insurance_center/*.xml",
            "deployfleet_ui/static/src/maintenance_planner/*.scss",
            "deployfleet_ui/static/src/maintenance_planner/*.js",
            "deployfleet_ui/static/src/maintenance_planner/*.xml",
        ],
    },
}
